[bot]
Token = ""
WebHook = ""
UseWebHook = false
ChatWhiteList = [ -123321123 ]
HttpPort = ":1212"
PollingTimeout = 10

[jira]
JiraLogin = ""
JiraPass = ""
JiraUrl = "jira.org"
JiraApiKeySearchUrl = ""