BotToken = "
ChatWhiteList = [ -32132111 ]

[jira]
JiraLogin = "user"
JiraPass = "passsword"
JiraUrl = "jira.team.icu"
JiraApiKeySearchUrl = "https://jjira.team.icu/rest/api/2/issue/"
_template.toml  
